#!/bin/bash
BIN_PATH="$HOME/.aptosup"

mkdir -p $BIN_PATH/tmp
curl -sSL https://raw.githubusercontent.com/LayerZero-Labs/aptosup/main/aptosup > $BIN_PATH/aptosup
chmod +x $BIN_PATH/aptosup

# Make sure that $BIN_PATH/aptosup exists
if [ ! -f "$BIN_PATH/aptosup" ]; then
    echo "aptosup binary not found in $BIN_PATH"
    exit 1
fi

echo "Aptos CLI Version Manager installed successfully"
echo "You can now use aptosup to manage your Aptos CLI versions"
echo "Run 'aptosup -l' to list all available versions"
echo "Run 'aptosup -v <version>' to install a specific version"

echo "########################################################"
echo "You might want to add the following to your ~/.zshrc or ~/.bashrc file for a more permanent solution:"
echo "Run the following command to add the path to your ~/.zshrc or ~/.bashrc file:"
echo "echo 'export PATH=\"$BIN_PATH:\$PATH\"' >> ~/.zshrc"
echo "source ~/.zshrc"
echo "########################################################"